language: objective-c
install:
  - brew install lcov
  - gem install lcoveralls
env: MRUBY_CONFIG=travis_config.rb
script: "./minirake all test"
after_success:
  - lcov -c -d build/debug -o coverage.info
  - lcoveralls --root .
